name: twilio_dart_example
description: Twilio example project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  twilio_dart:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
